spring.application.name=car_dealership_backend

spring.datasource.url=jdbc:sqlite:car_dealership.db
spring.datasource.driver-class-name=org.sqlite.JDBC

jwt.secret=MyVerySecretKeyForIncubyteAssessment2026MyVerySecretKey
jwt.expiration=86400000

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true